### ISSUE TITLE
papered over bug in virtapt

### ISSUE THREAD

**Issue by torbenh3** [Linutronix/elbe#158] opened 2018-05-08 14:58 UTC
after 478b26e08550 ("pkgutils: dont fallback to nonvirtapt code, when virtapt is avail") was applied.
a bug in virtapt was uncovered. Which was handled by dumb fallback Code.
To fix this problem the commit was reverted:
41f7e09e6fd6 ("Revert "pkgutils: dont fallback to nonvirtapt code, when virtapt is avail"")

`   multiprocessing.managers.RemoteError:
    ---------------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/managers.py", line 207, in handle_request
        result = func(c, *args, **kwds)
      File "/usr/lib/python2.7/multiprocessing/managers.py", line 386, in create
        obj = callable(*args, **kwds)
      File "/home/jogness/tmpfs/elbe/elbepack/virtapt.py", line 97, in __init__
        self.cache = apt_pkg.Cache()
    Error: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The value 'jessie' is invalid for APT::Default-Release as such a release is not available in the sources
    ---------------------------------------------------------------------------

`

**Comment by manut** [comment] 2018-05-08 15:25
duplicate of #139

**Closed by manut** 2018-05-08 15:25 UTC
Labels: duplicate
